server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
